require "user.options"
require "user.keybinds"
require "user.plugins"
require "user.theme"
require "user.nvimtree"
require "user.airline"
-- require "user.whichkey"
require "user.cmp"
require "user.coc"
require "user.metals"
require "user.indentblankline"
require "user.lsp-config"
require "user.treesitter"
require "user.autocmd"
require "user.symbols-outline"

